import Head from "next/head";
import Presentation from "../components/Presentation";
import { Team } from "../components/Team";

import styles from "../styles/Presentation.module.css";

export default function Home() {
  return (
    <div className={styles.back}>
      <Head>
        <title>Greedy Goblins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Presentation />
      <hr className={styles.line + " m-0 p-0 text-gold"}></hr>
      <Team />
    </div>
  );
}
